blank_issues_enabled: true
contact_links:
  - name: Discord Community
    url: https://discord.gg/sNKr7fwHUr
    about: Join our Discord for general questions and discussions
  - name: Steam Workshop
    url: https://steamcommunity.com/sharedfiles/filedetails/?id=2971219389
    about: Download the mod and leave feedback